name: Publish
permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }} 
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish